# Generated by Django 4.2.7 on 2023-11-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_alter_schedule_day_alter_schedule_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('student_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.studentworker')),
            ],
        ),
    ]
